### ISSUE TITLE
Privacy Statement

### ISSUE THREAD

**Issue by timfi** [infomark-org/infomark-backend#15]
We've been made aware that the privacy statement this project provides is both entirely static as well as partially faulty.
There are some `[FILLME]`s scattered around that need some attention and the linked Mail—not the `datenschutz@uni-tuebingen.de` one—is out of place.
Providing an entirely dynamic privacy statement is out of scope here, but some extra attention to this in the project's documentation could be of great help to users.

**Comment by PatWie** [comment]
What about changing the file https://github.com/infomark-org/infomark/blob/master/files/common/privacy_statement.md
as in https://github.com/infomark-org/infomark/commit/40057b89d49d85bb608a1f611e485d53b4a34c85 

3 years ago, I reached out to the Datenschutzbeauftragten and simply copied their version. When switching to informark-org the template has been changed into a more generic version.

I agree we should add this to the documentation.

**Comment by PatWie** [comment]
See #28
